[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_staking = "C6WghYhY8D4FGcVEU79DqzrbvsPvF7XEJVz8nB9UuYMV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/pranav/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
