[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "8o4NHsfNw24k9Ln9wKm24PsbRut5PYy3g6QmzH7BmcRk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
